version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - db

  api-test:
    build: .
    command: pipenv run pytest
    volumes:
      - .:/app
    env_file: ".env"
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
